
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xnn_inference.h"

/*
* The configuration table for devices
*/

XNn_inference_Config XNn_inference_ConfigTable[XPAR_XNN_INFERENCE_NUM_INSTANCES] =
{
	{
		XPAR_NN_INFERENCE_0_DEVICE_ID,
		XPAR_NN_INFERENCE_0_S_AXI_AXI_CPU_BASEADDR
	}
};


