-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity nn_inference_mat_mul is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_35017_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_35017_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_35017_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_35017_p_ce : OUT STD_LOGIC );
end;


architecture behav of nn_inference_mat_mul is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_pp2_stage0 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_pp3_stage0 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv6_4 : STD_LOGIC_VECTOR (5 downto 0) := "000100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal layer7_weights_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal layer7_weights_ce0 : STD_LOGIC;
    signal layer7_weights_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_0_reg_185 : STD_LOGIC_VECTOR (3 downto 0);
    signal sum_0_reg_196 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_1_reg_209 : STD_LOGIC_VECTOR (3 downto 0);
    signal sum_19_reg_220 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_2_reg_233 : STD_LOGIC_VECTOR (3 downto 0);
    signal sum_2_reg_244 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_3_reg_257 : STD_LOGIC_VECTOR (3 downto 0);
    signal sum_3_reg_268 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln70_reg_686 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state12_pp1_stage0_iter0 : BOOLEAN;
    signal ap_block_state13_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_state14_pp1_stage0_iter2 : BOOLEAN;
    signal ap_block_state15_pp1_stage0_iter3 : BOOLEAN;
    signal ap_block_state16_pp1_stage0_iter4 : BOOLEAN;
    signal ap_block_state17_pp1_stage0_iter5 : BOOLEAN;
    signal ap_block_state18_pp1_stage0_iter6 : BOOLEAN;
    signal ap_block_state19_pp1_stage0_iter7 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal ap_block_state21_pp2_stage0_iter0 : BOOLEAN;
    signal ap_block_state22_pp2_stage0_iter1 : BOOLEAN;
    signal ap_block_state23_pp2_stage0_iter2 : BOOLEAN;
    signal ap_block_state24_pp2_stage0_iter3 : BOOLEAN;
    signal ap_block_state25_pp2_stage0_iter4 : BOOLEAN;
    signal ap_block_state26_pp2_stage0_iter5 : BOOLEAN;
    signal ap_block_state27_pp2_stage0_iter6 : BOOLEAN;
    signal ap_block_state28_pp2_stage0_iter7 : BOOLEAN;
    signal ap_block_pp2_stage0_11001 : BOOLEAN;
    signal ap_block_state30_pp3_stage0_iter0 : BOOLEAN;
    signal ap_block_state31_pp3_stage0_iter1 : BOOLEAN;
    signal ap_block_state32_pp3_stage0_iter2 : BOOLEAN;
    signal ap_block_state33_pp3_stage0_iter3 : BOOLEAN;
    signal ap_block_state34_pp3_stage0_iter4 : BOOLEAN;
    signal ap_block_state35_pp3_stage0_iter5 : BOOLEAN;
    signal ap_block_state36_pp3_stage0_iter6 : BOOLEAN;
    signal ap_block_state37_pp3_stage0_iter7 : BOOLEAN;
    signal ap_block_pp3_stage0_11001 : BOOLEAN;
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal icmp_ln70_1_reg_731 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp2_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp2_stage0 : signal is "none";
    signal ap_enable_reg_pp2_iter1 : STD_LOGIC := '0';
    signal icmp_ln70_2_reg_776 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp3_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp3_stage0 : signal is "none";
    signal ap_enable_reg_pp3_iter1 : STD_LOGIC := '0';
    signal icmp_ln70_3_reg_821 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_281_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_297 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal icmp_ln70_reg_686_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp1_iter4 : STD_LOGIC := '0';
    signal icmp_ln70_1_reg_731_pp1_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp2_iter4 : STD_LOGIC := '0';
    signal icmp_ln70_2_reg_776_pp2_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp3_iter4 : STD_LOGIC := '0';
    signal icmp_ln70_3_reg_821_pp3_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_fu_301_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal zext_ln66_fu_307_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln66_reg_658 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln66_fu_311_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln66_reg_663 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl_cast_fu_323_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl_cast_reg_670 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_fu_333_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln70_reg_675 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln70_fu_337_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln70_reg_680 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal add_ln70_reg_680_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln70_reg_680_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln70_reg_680_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln70_reg_680_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln70_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_reg_686_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_reg_686_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_reg_686_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_reg_686_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_reg_686_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_382_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal or_ln66_cast10_fu_395_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln66_cast10_reg_710 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal p_shl2_cast_fu_407_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl2_cast_reg_715 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_1_fu_419_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln70_1_reg_720 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln70_1_fu_423_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln70_1_reg_725 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal add_ln70_1_reg_725_pp1_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln70_1_reg_725_pp1_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln70_1_reg_725_pp1_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln70_1_reg_725_pp1_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln70_1_fu_429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_1_reg_731_pp1_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_1_reg_731_pp1_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_1_reg_731_pp1_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_1_reg_731_pp1_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_1_reg_731_pp1_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_468_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp1_iter7 : STD_LOGIC := '0';
    signal or_ln66_7_cast12_fu_481_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln66_7_cast12_reg_755 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal p_shl4_cast_fu_493_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl4_cast_reg_760 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_2_fu_505_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln70_2_reg_765 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln70_2_fu_509_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln70_2_reg_770 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp2_iter0 : STD_LOGIC := '0';
    signal add_ln70_2_reg_770_pp2_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln70_2_reg_770_pp2_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln70_2_reg_770_pp2_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln70_2_reg_770_pp2_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln70_2_fu_515_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_2_reg_776_pp2_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_2_reg_776_pp2_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_2_reg_776_pp2_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_2_reg_776_pp2_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_2_reg_776_pp2_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_554_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp2_iter7 : STD_LOGIC := '0';
    signal or_ln66_8_cast14_fu_567_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln66_8_cast14_reg_800 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state29 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state29 : signal is "none";
    signal p_shl6_cast_fu_579_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl6_cast_reg_805 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_3_fu_591_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln70_3_reg_810 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln70_3_fu_595_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln70_3_reg_815 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp3_iter0 : STD_LOGIC := '0';
    signal add_ln70_3_reg_815_pp3_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln70_3_reg_815_pp3_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln70_3_reg_815_pp3_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln70_3_reg_815_pp3_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln70_3_fu_601_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_3_reg_821_pp3_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_3_reg_821_pp3_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_3_reg_821_pp3_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_3_reg_821_pp3_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_3_reg_821_pp3_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_640_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp3_iter7 : STD_LOGIC := '0';
    signal add_ln66_fu_648_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state38 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state38 : signal is "none";
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state3 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_exit_iter0_state12 : STD_LOGIC;
    signal ap_enable_reg_pp1_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter6 : STD_LOGIC := '0';
    signal ap_block_pp2_stage0_subdone : BOOLEAN;
    signal ap_condition_pp2_exit_iter0_state21 : STD_LOGIC;
    signal ap_enable_reg_pp2_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp2_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp2_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp2_iter6 : STD_LOGIC := '0';
    signal ap_block_pp3_stage0_subdone : BOOLEAN;
    signal ap_condition_pp3_exit_iter0_state30 : STD_LOGIC;
    signal ap_enable_reg_pp3_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp3_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp3_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp3_iter6 : STD_LOGIC := '0';
    signal i_0_reg_173 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_mux_j_0_phi_fu_189_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_mux_j_1_phi_fu_213_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal ap_phi_mux_j_2_phi_fu_237_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp2_stage0 : BOOLEAN;
    signal ap_phi_mux_j_3_phi_fu_261_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp3_stage0 : BOOLEAN;
    signal zext_ln72_7_fu_372_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_0_cast9_fu_349_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln72_9_fu_458_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast11_fu_435_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln72_11_fu_544_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_2_cast13_fu_521_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln72_13_fu_630_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_3_cast15_fu_607_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_281_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_281_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_shl_fu_315_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_96_fu_327_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal j_0_cast_fu_354_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln72_3_fu_358_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln72_fu_363_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln72_fu_367_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln66_fu_390_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl2_fu_399_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl3_fu_411_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal j_1_cast_fu_440_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln72_4_fu_444_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln72_8_fu_449_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln72_5_fu_453_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln66_5_fu_476_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl4_fu_485_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl5_fu_497_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal j_2_cast_fu_526_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln72_6_fu_530_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln72_10_fu_535_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln72_7_fu_539_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_554_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln66_6_fu_562_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl6_fu_571_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl7_fu_583_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal j_3_cast_fu_612_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln72_8_fu_616_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln72_12_fu_621_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln72_9_fu_625_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_640_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_281_ce : STD_LOGIC;
    signal grp_fu_382_in_valid : STD_LOGIC;
    signal grp_fu_468_in_valid : STD_LOGIC;
    signal grp_fu_554_in_valid : STD_LOGIC;
    signal grp_fu_640_in_valid : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;
    signal ap_idle_pp2 : STD_LOGIC;
    signal ap_enable_pp2 : STD_LOGIC;
    signal ap_idle_pp3 : STD_LOGIC;
    signal ap_enable_pp3 : STD_LOGIC;
    signal grp_fu_382_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_468_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_554_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_640_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component nn_inference_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_facc_32ns_32ns_1ns_32_3_no_dsp_1 IS
    generic (
        DWIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        ce : IN STD_LOGIC;
        in_data : IN STD_LOGIC_VECTOR (31 downto 0);
        in_last : IN STD_LOGIC_VECTOR (0 downto 0);
        in_valid : IN STD_LOGIC;
        out_data : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_mat_mul_layer7_weights IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    layer7_weights_U : component nn_inference_mat_mul_layer7_weights
    generic map (
        DataWidth => 32,
        AddressRange => 320,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => layer7_weights_address0,
        ce0 => layer7_weights_ce0,
        q0 => layer7_weights_q0);

    facc_32ns_32ns_1ns_32_3_no_dsp_1_U63 : component nn_inference_facc_32ns_32ns_1ns_32_3_no_dsp_1
    generic map (
        DWIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        ce => ap_const_logic_1,
        in_data => reg_297,
        in_last => grp_fu_382_p2,
        in_valid => grp_fu_382_in_valid,
        out_data => grp_fu_382_p3);

    facc_32ns_32ns_1ns_32_3_no_dsp_1_U64 : component nn_inference_facc_32ns_32ns_1ns_32_3_no_dsp_1
    generic map (
        DWIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        ce => ap_const_logic_1,
        in_data => reg_297,
        in_last => grp_fu_468_p2,
        in_valid => grp_fu_468_in_valid,
        out_data => grp_fu_468_p3);

    facc_32ns_32ns_1ns_32_3_no_dsp_1_U65 : component nn_inference_facc_32ns_32ns_1ns_32_3_no_dsp_1
    generic map (
        DWIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        ce => ap_const_logic_1,
        in_data => reg_297,
        in_last => grp_fu_554_p2,
        in_valid => grp_fu_554_in_valid,
        out_data => grp_fu_554_p3);

    facc_32ns_32ns_1ns_32_3_no_dsp_1_U66 : component nn_inference_facc_32ns_32ns_1ns_32_3_no_dsp_1
    generic map (
        DWIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        ce => ap_const_logic_1,
        in_data => reg_297,
        in_last => grp_fu_640_p2,
        in_valid => grp_fu_640_in_valid,
        out_data => grp_fu_640_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((icmp_ln66_fu_301_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state3);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                elsif (((icmp_ln66_fu_301_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state12) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp1_exit_iter0_state12)) then 
                        ap_enable_reg_pp1_iter1 <= (ap_const_logic_1 xor ap_condition_pp1_exit_iter0_state12);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter6 <= ap_enable_reg_pp1_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter7 <= ap_enable_reg_pp1_iter6;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    ap_enable_reg_pp1_iter7 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp2_exit_iter0_state21) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
                    ap_enable_reg_pp2_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
                    ap_enable_reg_pp2_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp2_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp2_exit_iter0_state21)) then 
                        ap_enable_reg_pp2_iter1 <= (ap_const_logic_1 xor ap_condition_pp2_exit_iter0_state21);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp2_stage0_subdone)) then 
                    ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp2_stage0_subdone)) then 
                    ap_enable_reg_pp2_iter3 <= ap_enable_reg_pp2_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp2_stage0_subdone)) then 
                    ap_enable_reg_pp2_iter4 <= ap_enable_reg_pp2_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp2_stage0_subdone)) then 
                    ap_enable_reg_pp2_iter5 <= ap_enable_reg_pp2_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp2_stage0_subdone)) then 
                    ap_enable_reg_pp2_iter6 <= ap_enable_reg_pp2_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp2_stage0_subdone)) then 
                    ap_enable_reg_pp2_iter7 <= ap_enable_reg_pp2_iter6;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
                    ap_enable_reg_pp2_iter7 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp3_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp3_exit_iter0_state30) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then 
                    ap_enable_reg_pp3_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state29)) then 
                    ap_enable_reg_pp3_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp3_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp3_exit_iter0_state30)) then 
                        ap_enable_reg_pp3_iter1 <= (ap_const_logic_1 xor ap_condition_pp3_exit_iter0_state30);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp3_stage0_subdone)) then 
                    ap_enable_reg_pp3_iter2 <= ap_enable_reg_pp3_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp3_stage0_subdone)) then 
                    ap_enable_reg_pp3_iter3 <= ap_enable_reg_pp3_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp3_stage0_subdone)) then 
                    ap_enable_reg_pp3_iter4 <= ap_enable_reg_pp3_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp3_stage0_subdone)) then 
                    ap_enable_reg_pp3_iter5 <= ap_enable_reg_pp3_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp3_stage0_subdone)) then 
                    ap_enable_reg_pp3_iter6 <= ap_enable_reg_pp3_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp3_stage0_subdone)) then 
                    ap_enable_reg_pp3_iter7 <= ap_enable_reg_pp3_iter6;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state29)) then 
                    ap_enable_reg_pp3_iter7 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_0_reg_173_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_0_reg_173 <= ap_const_lv6_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
                i_0_reg_173 <= add_ln66_fu_648_p2;
            end if; 
        end if;
    end process;

    j_0_reg_185_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln66_fu_301_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_0_reg_185 <= ap_const_lv4_0;
            elsif (((icmp_ln70_reg_686 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                j_0_reg_185 <= add_ln70_reg_680;
            end if; 
        end if;
    end process;

    j_1_reg_209_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                j_1_reg_209 <= ap_const_lv4_0;
            elsif (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (icmp_ln70_1_reg_731 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1))) then 
                j_1_reg_209 <= add_ln70_1_reg_725;
            end if; 
        end if;
    end process;

    j_2_reg_233_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
                j_2_reg_233 <= ap_const_lv4_0;
            elsif (((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (icmp_ln70_2_reg_776 = ap_const_lv1_0) and (ap_enable_reg_pp2_iter1 = ap_const_logic_1))) then 
                j_2_reg_233 <= add_ln70_2_reg_770;
            end if; 
        end if;
    end process;

    j_3_reg_257_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state29)) then 
                j_3_reg_257 <= ap_const_lv4_0;
            elsif (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (icmp_ln70_3_reg_821 = ap_const_lv1_0) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1))) then 
                j_3_reg_257 <= add_ln70_3_reg_815;
            end if; 
        end if;
    end process;

    sum_0_reg_196_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln66_fu_301_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                sum_0_reg_196 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (icmp_ln70_reg_686_pp0_iter6_reg = ap_const_lv1_0))) then 
                sum_0_reg_196 <= grp_fu_382_p3;
            end if; 
        end if;
    end process;

    sum_19_reg_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                sum_19_reg_220 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter7 = ap_const_logic_1) and (icmp_ln70_1_reg_731_pp1_iter6_reg = ap_const_lv1_0))) then 
                sum_19_reg_220 <= grp_fu_468_p3;
            end if; 
        end if;
    end process;

    sum_2_reg_244_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
                sum_2_reg_244 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_enable_reg_pp2_iter7 = ap_const_logic_1) and (icmp_ln70_2_reg_776_pp2_iter6_reg = ap_const_lv1_0))) then 
                sum_2_reg_244 <= grp_fu_554_p3;
            end if; 
        end if;
    end process;

    sum_3_reg_268_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state29)) then 
                sum_3_reg_268 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter7 = ap_const_logic_1) and (icmp_ln70_3_reg_821_pp3_iter6_reg = ap_const_lv1_0))) then 
                sum_3_reg_268 <= grp_fu_640_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                add_ln70_1_reg_725 <= add_ln70_1_fu_423_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                add_ln70_1_reg_725_pp1_iter1_reg <= add_ln70_1_reg_725;
                icmp_ln70_1_reg_731 <= icmp_ln70_1_fu_429_p2;
                icmp_ln70_1_reg_731_pp1_iter1_reg <= icmp_ln70_1_reg_731;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp1_stage0_11001)) then
                add_ln70_1_reg_725_pp1_iter2_reg <= add_ln70_1_reg_725_pp1_iter1_reg;
                add_ln70_1_reg_725_pp1_iter3_reg <= add_ln70_1_reg_725_pp1_iter2_reg;
                add_ln70_1_reg_725_pp1_iter4_reg <= add_ln70_1_reg_725_pp1_iter3_reg;
                icmp_ln70_1_reg_731_pp1_iter2_reg <= icmp_ln70_1_reg_731_pp1_iter1_reg;
                icmp_ln70_1_reg_731_pp1_iter3_reg <= icmp_ln70_1_reg_731_pp1_iter2_reg;
                icmp_ln70_1_reg_731_pp1_iter4_reg <= icmp_ln70_1_reg_731_pp1_iter3_reg;
                icmp_ln70_1_reg_731_pp1_iter5_reg <= icmp_ln70_1_reg_731_pp1_iter4_reg;
                icmp_ln70_1_reg_731_pp1_iter6_reg <= icmp_ln70_1_reg_731_pp1_iter5_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then
                add_ln70_2_reg_770 <= add_ln70_2_fu_509_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then
                add_ln70_2_reg_770_pp2_iter1_reg <= add_ln70_2_reg_770;
                icmp_ln70_2_reg_776 <= icmp_ln70_2_fu_515_p2;
                icmp_ln70_2_reg_776_pp2_iter1_reg <= icmp_ln70_2_reg_776;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp2_stage0_11001)) then
                add_ln70_2_reg_770_pp2_iter2_reg <= add_ln70_2_reg_770_pp2_iter1_reg;
                add_ln70_2_reg_770_pp2_iter3_reg <= add_ln70_2_reg_770_pp2_iter2_reg;
                add_ln70_2_reg_770_pp2_iter4_reg <= add_ln70_2_reg_770_pp2_iter3_reg;
                icmp_ln70_2_reg_776_pp2_iter2_reg <= icmp_ln70_2_reg_776_pp2_iter1_reg;
                icmp_ln70_2_reg_776_pp2_iter3_reg <= icmp_ln70_2_reg_776_pp2_iter2_reg;
                icmp_ln70_2_reg_776_pp2_iter4_reg <= icmp_ln70_2_reg_776_pp2_iter3_reg;
                icmp_ln70_2_reg_776_pp2_iter5_reg <= icmp_ln70_2_reg_776_pp2_iter4_reg;
                icmp_ln70_2_reg_776_pp2_iter6_reg <= icmp_ln70_2_reg_776_pp2_iter5_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then
                add_ln70_3_reg_815 <= add_ln70_3_fu_595_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then
                add_ln70_3_reg_815_pp3_iter1_reg <= add_ln70_3_reg_815;
                icmp_ln70_3_reg_821 <= icmp_ln70_3_fu_601_p2;
                icmp_ln70_3_reg_821_pp3_iter1_reg <= icmp_ln70_3_reg_821;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp3_stage0_11001)) then
                add_ln70_3_reg_815_pp3_iter2_reg <= add_ln70_3_reg_815_pp3_iter1_reg;
                add_ln70_3_reg_815_pp3_iter3_reg <= add_ln70_3_reg_815_pp3_iter2_reg;
                add_ln70_3_reg_815_pp3_iter4_reg <= add_ln70_3_reg_815_pp3_iter3_reg;
                icmp_ln70_3_reg_821_pp3_iter2_reg <= icmp_ln70_3_reg_821_pp3_iter1_reg;
                icmp_ln70_3_reg_821_pp3_iter3_reg <= icmp_ln70_3_reg_821_pp3_iter2_reg;
                icmp_ln70_3_reg_821_pp3_iter4_reg <= icmp_ln70_3_reg_821_pp3_iter3_reg;
                icmp_ln70_3_reg_821_pp3_iter5_reg <= icmp_ln70_3_reg_821_pp3_iter4_reg;
                icmp_ln70_3_reg_821_pp3_iter6_reg <= icmp_ln70_3_reg_821_pp3_iter5_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln70_reg_680 <= add_ln70_fu_337_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln70_reg_680_pp0_iter1_reg <= add_ln70_reg_680;
                icmp_ln70_reg_686 <= icmp_ln70_fu_343_p2;
                icmp_ln70_reg_686_pp0_iter1_reg <= icmp_ln70_reg_686;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln70_reg_680_pp0_iter2_reg <= add_ln70_reg_680_pp0_iter1_reg;
                add_ln70_reg_680_pp0_iter3_reg <= add_ln70_reg_680_pp0_iter2_reg;
                add_ln70_reg_680_pp0_iter4_reg <= add_ln70_reg_680_pp0_iter3_reg;
                icmp_ln70_reg_686_pp0_iter2_reg <= icmp_ln70_reg_686_pp0_iter1_reg;
                icmp_ln70_reg_686_pp0_iter3_reg <= icmp_ln70_reg_686_pp0_iter2_reg;
                icmp_ln70_reg_686_pp0_iter4_reg <= icmp_ln70_reg_686_pp0_iter3_reg;
                icmp_ln70_reg_686_pp0_iter5_reg <= icmp_ln70_reg_686_pp0_iter4_reg;
                icmp_ln70_reg_686_pp0_iter6_reg <= icmp_ln70_reg_686_pp0_iter5_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then
                    or_ln66_7_cast12_reg_755(0) <= or_ln66_7_cast12_fu_481_p1(0);    or_ln66_7_cast12_reg_755(4 downto 2) <= or_ln66_7_cast12_fu_481_p1(4 downto 2);
                    p_shl4_cast_reg_760(3) <= p_shl4_cast_fu_493_p1(3);    p_shl4_cast_reg_760(7 downto 5) <= p_shl4_cast_fu_493_p1(7 downto 5);
                    zext_ln70_2_reg_765(1) <= zext_ln70_2_fu_505_p1(1);    zext_ln70_2_reg_765(5 downto 3) <= zext_ln70_2_fu_505_p1(5 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state29)) then
                    or_ln66_8_cast14_reg_800(4 downto 2) <= or_ln66_8_cast14_fu_567_p1(4 downto 2);
                    p_shl6_cast_reg_805(7 downto 5) <= p_shl6_cast_fu_579_p1(7 downto 5);
                    zext_ln70_3_reg_810(5 downto 3) <= zext_ln70_3_fu_591_p1(5 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                    or_ln66_cast10_reg_710(4 downto 1) <= or_ln66_cast10_fu_395_p1(4 downto 1);
                    p_shl2_cast_reg_715(7 downto 4) <= p_shl2_cast_fu_407_p1(7 downto 4);
                    zext_ln70_1_reg_720(5 downto 2) <= zext_ln70_1_fu_419_p1(5 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln66_fu_301_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    p_shl_cast_reg_670(7 downto 3) <= p_shl_cast_fu_323_p1(7 downto 3);
                trunc_ln66_reg_663 <= trunc_ln66_fu_311_p1;
                    zext_ln66_reg_658(5 downto 0) <= zext_ln66_fu_307_p1(5 downto 0);
                    zext_ln70_reg_675(5 downto 1) <= zext_ln70_fu_333_p1(5 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln70_reg_686_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (icmp_ln70_3_reg_821_pp3_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp3_iter4 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (icmp_ln70_2_reg_776_pp2_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp2_iter4 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln70_1_reg_731_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1)))) then
                reg_297 <= grp_fu_35017_p_dout0;
            end if;
        end if;
    end process;
    zext_ln66_reg_658(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    p_shl_cast_reg_670(2 downto 0) <= "000";
    p_shl_cast_reg_670(8) <= '0';
    zext_ln70_reg_675(0) <= '0';
    zext_ln70_reg_675(6) <= '0';
    or_ln66_cast10_reg_710(0) <= '1';
    or_ln66_cast10_reg_710(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    p_shl2_cast_reg_715(3 downto 0) <= "1000";
    p_shl2_cast_reg_715(8) <= '0';
    zext_ln70_1_reg_720(1 downto 0) <= "10";
    zext_ln70_1_reg_720(6) <= '0';
    or_ln66_7_cast12_reg_755(1) <= '1';
    or_ln66_7_cast12_reg_755(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    p_shl4_cast_reg_760(2 downto 0) <= "000";
    p_shl4_cast_reg_760(4 downto 4) <= "1";
    p_shl4_cast_reg_760(8) <= '0';
    zext_ln70_2_reg_765(0) <= '0';
    zext_ln70_2_reg_765(2 downto 2) <= "1";
    zext_ln70_2_reg_765(6) <= '0';
    or_ln66_8_cast14_reg_800(1 downto 0) <= "11";
    or_ln66_8_cast14_reg_800(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    p_shl6_cast_reg_805(4 downto 0) <= "11000";
    p_shl6_cast_reg_805(8) <= '0';
    zext_ln70_3_reg_810(2 downto 0) <= "110";
    zext_ln70_3_reg_810(6) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter1, ap_enable_reg_pp1_iter1, ap_enable_reg_pp2_iter1, ap_enable_reg_pp3_iter1, icmp_ln66_fu_301_p2, ap_CS_fsm_state2, ap_enable_reg_pp0_iter0, icmp_ln70_fu_343_p2, ap_enable_reg_pp0_iter7, ap_enable_reg_pp1_iter0, icmp_ln70_1_fu_429_p2, ap_enable_reg_pp1_iter7, ap_enable_reg_pp2_iter0, icmp_ln70_2_fu_515_p2, ap_enable_reg_pp2_iter7, ap_enable_reg_pp3_iter0, icmp_ln70_3_fu_601_p2, ap_enable_reg_pp3_iter7, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter6, ap_block_pp1_stage0_subdone, ap_enable_reg_pp1_iter6, ap_block_pp2_stage0_subdone, ap_enable_reg_pp2_iter6, ap_block_pp3_stage0_subdone, ap_enable_reg_pp3_iter6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln66_fu_301_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (icmp_ln70_fu_343_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (icmp_ln70_fu_343_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
            when ap_ST_fsm_pp1_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (icmp_ln70_1_fu_429_p2 = ap_const_lv1_1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_0))) and not(((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter6 = ap_const_logic_0) and (ap_enable_reg_pp1_iter7 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif ((((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter6 = ap_const_logic_0) and (ap_enable_reg_pp1_iter7 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (icmp_ln70_1_fu_429_p2 = ap_const_lv1_1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
            when ap_ST_fsm_pp2_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (icmp_ln70_2_fu_515_p2 = ap_const_lv1_1) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_enable_reg_pp2_iter1 = ap_const_logic_0))) and not(((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_enable_reg_pp2_iter6 = ap_const_logic_0) and (ap_enable_reg_pp2_iter7 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
                elsif ((((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_enable_reg_pp2_iter6 = ap_const_logic_0) and (ap_enable_reg_pp2_iter7 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (icmp_ln70_2_fu_515_p2 = ap_const_lv1_1) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_enable_reg_pp2_iter1 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state29;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
                end if;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_pp3_stage0;
            when ap_ST_fsm_pp3_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp3_stage0_subdone) and (icmp_ln70_3_fu_601_p2 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_0))) and not(((ap_const_boolean_0 = ap_block_pp3_stage0_subdone) and (ap_enable_reg_pp3_iter6 = ap_const_logic_0) and (ap_enable_reg_pp3_iter7 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp3_stage0;
                elsif ((((ap_const_boolean_0 = ap_block_pp3_stage0_subdone) and (ap_enable_reg_pp3_iter6 = ap_const_logic_0) and (ap_enable_reg_pp3_iter7 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp3_stage0_subdone) and (icmp_ln70_3_fu_601_p2 = ap_const_lv1_1) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state38;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp3_stage0;
                end if;
            when ap_ST_fsm_state38 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    add_ln66_fu_648_p2 <= std_logic_vector(unsigned(i_0_reg_173) + unsigned(ap_const_lv6_4));
    add_ln70_1_fu_423_p2 <= std_logic_vector(unsigned(ap_phi_mux_j_1_phi_fu_213_p4) + unsigned(ap_const_lv4_1));
    add_ln70_2_fu_509_p2 <= std_logic_vector(unsigned(ap_phi_mux_j_2_phi_fu_237_p4) + unsigned(ap_const_lv4_1));
    add_ln70_3_fu_595_p2 <= std_logic_vector(unsigned(ap_phi_mux_j_3_phi_fu_261_p4) + unsigned(ap_const_lv4_1));
    add_ln70_fu_337_p2 <= std_logic_vector(unsigned(ap_phi_mux_j_0_phi_fu_189_p4) + unsigned(ap_const_lv4_1));
    add_ln72_3_fu_358_p2 <= std_logic_vector(unsigned(zext_ln70_reg_675) + unsigned(j_0_cast_fu_354_p1));
    add_ln72_4_fu_444_p2 <= std_logic_vector(unsigned(zext_ln70_1_reg_720) + unsigned(j_1_cast_fu_440_p1));
    add_ln72_5_fu_453_p2 <= std_logic_vector(unsigned(zext_ln72_8_fu_449_p1) + unsigned(p_shl2_cast_reg_715));
    add_ln72_6_fu_530_p2 <= std_logic_vector(unsigned(zext_ln70_2_reg_765) + unsigned(j_2_cast_fu_526_p1));
    add_ln72_7_fu_539_p2 <= std_logic_vector(unsigned(zext_ln72_10_fu_535_p1) + unsigned(p_shl4_cast_reg_760));
    add_ln72_8_fu_616_p2 <= std_logic_vector(unsigned(zext_ln70_3_reg_810) + unsigned(j_3_cast_fu_612_p1));
    add_ln72_9_fu_625_p2 <= std_logic_vector(unsigned(zext_ln72_12_fu_621_p1) + unsigned(p_shl6_cast_reg_805));
    add_ln72_fu_367_p2 <= std_logic_vector(unsigned(zext_ln72_fu_363_p1) + unsigned(p_shl_cast_reg_670));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(4);
    ap_CS_fsm_pp2_stage0 <= ap_CS_fsm(6);
    ap_CS_fsm_pp3_stage0 <= ap_CS_fsm(8);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(3);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(5);
    ap_CS_fsm_state29 <= ap_CS_fsm(7);
    ap_CS_fsm_state38 <= ap_CS_fsm(9);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp2_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp2_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp2_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp3_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp3_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp3_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp1_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp1_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp1_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp1_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp1_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp1_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp1_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp1_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state21_pp2_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state22_pp2_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state23_pp2_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state24_pp2_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state25_pp2_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state26_pp2_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state27_pp2_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state28_pp2_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state30_pp3_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state31_pp3_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state32_pp3_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state33_pp3_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state34_pp3_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state35_pp3_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state36_pp3_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state37_pp3_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state3_assign_proc : process(icmp_ln70_fu_343_p2)
    begin
        if ((icmp_ln70_fu_343_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp1_exit_iter0_state12_assign_proc : process(icmp_ln70_1_fu_429_p2)
    begin
        if ((icmp_ln70_1_fu_429_p2 = ap_const_lv1_1)) then 
            ap_condition_pp1_exit_iter0_state12 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter0_state12 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp2_exit_iter0_state21_assign_proc : process(icmp_ln70_2_fu_515_p2)
    begin
        if ((icmp_ln70_2_fu_515_p2 = ap_const_lv1_1)) then 
            ap_condition_pp2_exit_iter0_state21 <= ap_const_logic_1;
        else 
            ap_condition_pp2_exit_iter0_state21 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp3_exit_iter0_state30_assign_proc : process(icmp_ln70_3_fu_601_p2)
    begin
        if ((icmp_ln70_3_fu_601_p2 = ap_const_lv1_1)) then 
            ap_condition_pp3_exit_iter0_state30 <= ap_const_logic_1;
        else 
            ap_condition_pp3_exit_iter0_state30 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln66_fu_301_p2, ap_CS_fsm_state2)
    begin
        if ((((icmp_ln66_fu_301_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);
    ap_enable_pp2 <= (ap_idle_pp2 xor ap_const_logic_1);
    ap_enable_pp3 <= (ap_idle_pp3 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter4, ap_enable_reg_pp1_iter0, ap_enable_reg_pp1_iter7, ap_enable_reg_pp1_iter2, ap_enable_reg_pp1_iter3, ap_enable_reg_pp1_iter5, ap_enable_reg_pp1_iter6)
    begin
        if (((ap_enable_reg_pp1_iter6 = ap_const_logic_0) and (ap_enable_reg_pp1_iter5 = ap_const_logic_0) and (ap_enable_reg_pp1_iter3 = ap_const_logic_0) and (ap_enable_reg_pp1_iter2 = ap_const_logic_0) and (ap_enable_reg_pp1_iter7 = ap_const_logic_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp2_assign_proc : process(ap_enable_reg_pp2_iter1, ap_enable_reg_pp2_iter4, ap_enable_reg_pp2_iter0, ap_enable_reg_pp2_iter7, ap_enable_reg_pp2_iter2, ap_enable_reg_pp2_iter3, ap_enable_reg_pp2_iter5, ap_enable_reg_pp2_iter6)
    begin
        if (((ap_enable_reg_pp2_iter6 = ap_const_logic_0) and (ap_enable_reg_pp2_iter5 = ap_const_logic_0) and (ap_enable_reg_pp2_iter3 = ap_const_logic_0) and (ap_enable_reg_pp2_iter2 = ap_const_logic_0) and (ap_enable_reg_pp2_iter7 = ap_const_logic_0) and (ap_enable_reg_pp2_iter0 = ap_const_logic_0) and (ap_enable_reg_pp2_iter4 = ap_const_logic_0) and (ap_enable_reg_pp2_iter1 = ap_const_logic_0))) then 
            ap_idle_pp2 <= ap_const_logic_1;
        else 
            ap_idle_pp2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp3_assign_proc : process(ap_enable_reg_pp3_iter1, ap_enable_reg_pp3_iter4, ap_enable_reg_pp3_iter0, ap_enable_reg_pp3_iter7, ap_enable_reg_pp3_iter2, ap_enable_reg_pp3_iter3, ap_enable_reg_pp3_iter5, ap_enable_reg_pp3_iter6)
    begin
        if (((ap_enable_reg_pp3_iter6 = ap_const_logic_0) and (ap_enable_reg_pp3_iter5 = ap_const_logic_0) and (ap_enable_reg_pp3_iter3 = ap_const_logic_0) and (ap_enable_reg_pp3_iter2 = ap_const_logic_0) and (ap_enable_reg_pp3_iter7 = ap_const_logic_0) and (ap_enable_reg_pp3_iter0 = ap_const_logic_0) and (ap_enable_reg_pp3_iter4 = ap_const_logic_0) and (ap_enable_reg_pp3_iter1 = ap_const_logic_0))) then 
            ap_idle_pp3 <= ap_const_logic_1;
        else 
            ap_idle_pp3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_j_0_phi_fu_189_p4_assign_proc : process(j_0_reg_185, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln70_reg_686, add_ln70_reg_680, ap_block_pp0_stage0)
    begin
        if (((icmp_ln70_reg_686 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_j_0_phi_fu_189_p4 <= add_ln70_reg_680;
        else 
            ap_phi_mux_j_0_phi_fu_189_p4 <= j_0_reg_185;
        end if; 
    end process;


    ap_phi_mux_j_1_phi_fu_213_p4_assign_proc : process(j_1_reg_209, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln70_1_reg_731, add_ln70_1_reg_725, ap_block_pp1_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (icmp_ln70_1_reg_731 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_j_1_phi_fu_213_p4 <= add_ln70_1_reg_725;
        else 
            ap_phi_mux_j_1_phi_fu_213_p4 <= j_1_reg_209;
        end if; 
    end process;


    ap_phi_mux_j_2_phi_fu_237_p4_assign_proc : process(j_2_reg_233, ap_CS_fsm_pp2_stage0, ap_enable_reg_pp2_iter1, icmp_ln70_2_reg_776, add_ln70_2_reg_770, ap_block_pp2_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp2_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (icmp_ln70_2_reg_776 = ap_const_lv1_0) and (ap_enable_reg_pp2_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_j_2_phi_fu_237_p4 <= add_ln70_2_reg_770;
        else 
            ap_phi_mux_j_2_phi_fu_237_p4 <= j_2_reg_233;
        end if; 
    end process;


    ap_phi_mux_j_3_phi_fu_261_p4_assign_proc : process(j_3_reg_257, ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, icmp_ln70_3_reg_821, add_ln70_3_reg_815, ap_block_pp3_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (icmp_ln70_3_reg_821 = ap_const_lv1_0) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_j_3_phi_fu_261_p4 <= add_ln70_3_reg_815;
        else 
            ap_phi_mux_j_3_phi_fu_261_p4 <= j_3_reg_257;
        end if; 
    end process;


    ap_ready_assign_proc : process(icmp_ln66_fu_301_p2, ap_CS_fsm_state2)
    begin
        if (((icmp_ln66_fu_301_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    empty_96_fu_327_p2 <= std_logic_vector(shift_left(unsigned(i_0_reg_173),to_integer(unsigned('0' & ap_const_lv6_1(6-1 downto 0)))));
    grp_fu_281_ce <= ap_const_logic_1;
    grp_fu_281_p0 <= layer7_weights_q0;
    grp_fu_281_p1 <= input_r_q0;
    grp_fu_281_p2 <= grp_fu_35017_p_dout0;
    grp_fu_35017_p_ce <= ap_const_logic_1;
    grp_fu_35017_p_din0 <= layer7_weights_q0;
    grp_fu_35017_p_din1 <= input_r_q0;

    grp_fu_382_in_valid_assign_proc : process(icmp_ln70_reg_686_pp0_iter4_reg, ap_enable_reg_pp0_iter5, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln70_reg_686_pp0_iter4_reg = ap_const_lv1_0))) then 
            grp_fu_382_in_valid <= ap_const_logic_1;
        else 
            grp_fu_382_in_valid <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_382_p2 <= "1" when (add_ln70_reg_680_pp0_iter4_reg = ap_const_lv4_A) else "0";

    grp_fu_468_in_valid_assign_proc : process(icmp_ln70_1_reg_731_pp1_iter4_reg, ap_enable_reg_pp1_iter5, ap_block_pp1_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter5 = ap_const_logic_1) and (icmp_ln70_1_reg_731_pp1_iter4_reg = ap_const_lv1_0))) then 
            grp_fu_468_in_valid <= ap_const_logic_1;
        else 
            grp_fu_468_in_valid <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_468_p2 <= "1" when (add_ln70_1_reg_725_pp1_iter4_reg = ap_const_lv4_A) else "0";

    grp_fu_554_in_valid_assign_proc : process(icmp_ln70_2_reg_776_pp2_iter4_reg, ap_enable_reg_pp2_iter5, ap_block_pp2_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp2_stage0) and (ap_enable_reg_pp2_iter5 = ap_const_logic_1) and (icmp_ln70_2_reg_776_pp2_iter4_reg = ap_const_lv1_0))) then 
            grp_fu_554_in_valid <= ap_const_logic_1;
        else 
            grp_fu_554_in_valid <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_554_p2 <= "1" when (add_ln70_2_reg_770_pp2_iter4_reg = ap_const_lv4_A) else "0";

    grp_fu_640_in_valid_assign_proc : process(icmp_ln70_3_reg_821_pp3_iter4_reg, ap_enable_reg_pp3_iter5, ap_block_pp3_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_enable_reg_pp3_iter5 = ap_const_logic_1) and (icmp_ln70_3_reg_821_pp3_iter4_reg = ap_const_lv1_0))) then 
            grp_fu_640_in_valid <= ap_const_logic_1;
        else 
            grp_fu_640_in_valid <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_640_p2 <= "1" when (add_ln70_3_reg_815_pp3_iter4_reg = ap_const_lv4_A) else "0";
    icmp_ln66_fu_301_p2 <= "1" when (i_0_reg_173 = ap_const_lv6_20) else "0";
    icmp_ln70_1_fu_429_p2 <= "1" when (ap_phi_mux_j_1_phi_fu_213_p4 = ap_const_lv4_A) else "0";
    icmp_ln70_2_fu_515_p2 <= "1" when (ap_phi_mux_j_2_phi_fu_237_p4 = ap_const_lv4_A) else "0";
    icmp_ln70_3_fu_601_p2 <= "1" when (ap_phi_mux_j_3_phi_fu_261_p4 = ap_const_lv4_A) else "0";
    icmp_ln70_fu_343_p2 <= "1" when (ap_phi_mux_j_0_phi_fu_189_p4 = ap_const_lv4_A) else "0";

    input_r_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp1_stage0, ap_CS_fsm_pp2_stage0, ap_CS_fsm_pp3_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp1_iter0, ap_enable_reg_pp2_iter0, ap_enable_reg_pp3_iter0, ap_block_pp0_stage0, ap_block_pp1_stage0, ap_block_pp2_stage0, ap_block_pp3_stage0, j_0_cast9_fu_349_p1, j_1_cast11_fu_435_p1, j_2_cast13_fu_521_p1, j_3_cast15_fu_607_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then 
            input_r_address0 <= j_3_cast15_fu_607_p1(4 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp2_stage0) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
            input_r_address0 <= j_2_cast13_fu_521_p1(4 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            input_r_address0 <= j_1_cast11_fu_435_p1(4 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_address0 <= j_0_cast9_fu_349_p1(4 - 1 downto 0);
        else 
            input_r_address0 <= "XXXX";
        end if; 
    end process;


    input_r_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_block_pp1_stage0_11001, ap_block_pp2_stage0_11001, ap_block_pp3_stage0_11001, ap_CS_fsm_pp1_stage0, ap_CS_fsm_pp2_stage0, ap_CS_fsm_pp3_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp1_iter0, ap_enable_reg_pp2_iter0, ap_enable_reg_pp3_iter0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0)) or ((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0)) or ((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)))) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    j_0_cast9_fu_349_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_j_0_phi_fu_189_p4),64));
    j_0_cast_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_j_0_phi_fu_189_p4),7));
    j_1_cast11_fu_435_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_j_1_phi_fu_213_p4),64));
    j_1_cast_fu_440_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_j_1_phi_fu_213_p4),7));
    j_2_cast13_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_j_2_phi_fu_237_p4),64));
    j_2_cast_fu_526_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_j_2_phi_fu_237_p4),7));
    j_3_cast15_fu_607_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_j_3_phi_fu_261_p4),64));
    j_3_cast_fu_612_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_j_3_phi_fu_261_p4),7));

    layer7_weights_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp1_stage0, ap_CS_fsm_pp2_stage0, ap_CS_fsm_pp3_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp1_iter0, ap_enable_reg_pp2_iter0, ap_enable_reg_pp3_iter0, ap_block_pp0_stage0, ap_block_pp1_stage0, ap_block_pp2_stage0, ap_block_pp3_stage0, zext_ln72_7_fu_372_p1, zext_ln72_9_fu_458_p1, zext_ln72_11_fu_544_p1, zext_ln72_13_fu_630_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then 
            layer7_weights_address0 <= zext_ln72_13_fu_630_p1(9 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp2_stage0) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
            layer7_weights_address0 <= zext_ln72_11_fu_544_p1(9 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            layer7_weights_address0 <= zext_ln72_9_fu_458_p1(9 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer7_weights_address0 <= zext_ln72_7_fu_372_p1(9 - 1 downto 0);
        else 
            layer7_weights_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    layer7_weights_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_block_pp1_stage0_11001, ap_block_pp2_stage0_11001, ap_block_pp3_stage0_11001, ap_CS_fsm_pp1_stage0, ap_CS_fsm_pp2_stage0, ap_CS_fsm_pp3_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp1_iter0, ap_enable_reg_pp2_iter0, ap_enable_reg_pp3_iter0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0)) or ((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0)) or ((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)))) then 
            layer7_weights_ce0 <= ap_const_logic_1;
        else 
            layer7_weights_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln66_5_fu_476_p2 <= (trunc_ln66_reg_663 or ap_const_lv5_2);
    or_ln66_6_fu_562_p2 <= (trunc_ln66_reg_663 or ap_const_lv5_3);
    or_ln66_7_cast12_fu_481_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln66_5_fu_476_p2),64));
    or_ln66_8_cast14_fu_567_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln66_6_fu_562_p2),64));
    or_ln66_cast10_fu_395_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln66_fu_390_p2),64));
    or_ln66_fu_390_p2 <= (trunc_ln66_reg_663 or ap_const_lv5_1);

    output_r_address0_assign_proc : process(zext_ln66_reg_658, or_ln66_cast10_reg_710, ap_CS_fsm_state11, or_ln66_7_cast12_reg_755, ap_CS_fsm_state20, or_ln66_8_cast14_reg_800, ap_CS_fsm_state29, ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            output_r_address0 <= or_ln66_8_cast14_reg_800(11 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state29)) then 
            output_r_address0 <= or_ln66_7_cast12_reg_755(11 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            output_r_address0 <= or_ln66_cast10_reg_710(11 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            output_r_address0 <= zext_ln66_reg_658(11 - 1 downto 0);
        else 
            output_r_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;


    output_r_ce0_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state20, ap_CS_fsm_state29, ap_CS_fsm_state38)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state38) or (ap_const_logic_1 = ap_CS_fsm_state29) or (ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            output_r_ce0 <= ap_const_logic_1;
        else 
            output_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    output_r_d0_assign_proc : process(sum_0_reg_196, sum_19_reg_220, sum_2_reg_244, sum_3_reg_268, ap_CS_fsm_state11, ap_CS_fsm_state20, ap_CS_fsm_state29, ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            output_r_d0 <= sum_3_reg_268;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state29)) then 
            output_r_d0 <= sum_2_reg_244;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            output_r_d0 <= sum_19_reg_220;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            output_r_d0 <= sum_0_reg_196;
        else 
            output_r_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    output_r_we0_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state20, ap_CS_fsm_state29, ap_CS_fsm_state38)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state38) or (ap_const_logic_1 = ap_CS_fsm_state29) or (ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            output_r_we0 <= ap_const_logic_1;
        else 
            output_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_shl2_cast_fu_407_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl2_fu_399_p3),9));
    p_shl2_fu_399_p3 <= (or_ln66_fu_390_p2 & ap_const_lv3_0);
    p_shl3_fu_411_p3 <= (or_ln66_fu_390_p2 & ap_const_lv1_0);
    p_shl4_cast_fu_493_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl4_fu_485_p3),9));
    p_shl4_fu_485_p3 <= (or_ln66_5_fu_476_p2 & ap_const_lv3_0);
    p_shl5_fu_497_p3 <= (or_ln66_5_fu_476_p2 & ap_const_lv1_0);
    p_shl6_cast_fu_579_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl6_fu_571_p3),9));
    p_shl6_fu_571_p3 <= (or_ln66_6_fu_562_p2 & ap_const_lv3_0);
    p_shl7_fu_583_p3 <= (or_ln66_6_fu_562_p2 & ap_const_lv1_0);
    p_shl_cast_fu_323_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl_fu_315_p3),9));
    p_shl_fu_315_p3 <= (trunc_ln66_fu_311_p1 & ap_const_lv3_0);
    trunc_ln66_fu_311_p1 <= i_0_reg_173(5 - 1 downto 0);
    zext_ln66_fu_307_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_reg_173),64));
    zext_ln70_1_fu_419_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl3_fu_411_p3),7));
    zext_ln70_2_fu_505_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl5_fu_497_p3),7));
    zext_ln70_3_fu_591_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl7_fu_583_p3),7));
    zext_ln70_fu_333_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_96_fu_327_p2),7));
    zext_ln72_10_fu_535_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln72_6_fu_530_p2),9));
    zext_ln72_11_fu_544_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln72_7_fu_539_p2),64));
    zext_ln72_12_fu_621_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln72_8_fu_616_p2),9));
    zext_ln72_13_fu_630_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln72_9_fu_625_p2),64));
    zext_ln72_7_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln72_fu_367_p2),64));
    zext_ln72_8_fu_449_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln72_4_fu_444_p2),9));
    zext_ln72_9_fu_458_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln72_5_fu_453_p2),64));
    zext_ln72_fu_363_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln72_3_fu_358_p2),9));
end behav;
